import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import { Noto_Sans_Thai } from 'next/font/google';
import "./globals.css";

const notoSansThai = Noto_Sans_Thai({
  subsets: ['thai', 'latin'], // ระบุ Thai และ Latin
  weight: ['400', '700'],     // เลือกน้ำหนักฟอนต์
  display: 'swap',
});

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="th">
      <body className={`${notoSansThai.className} antialiased`}>
        {children}
      </body>
    </html>
  );
}
